### ISSUE TITLE
can't set minsize

### ISSUE THREAD

**Issue by fireba11** [fi-ts/cloudctl#163]
Example for cluster create shows "--minsize 2".
Is that only available on cluster creation? If i try to update my cluster with "--minsize 2" it says that is only available to the provider ;-)
If not fix the example please :-)

**Comment by majst01** [comment]
To be able to set minsize you must be member of the provider team. The reason is that the accounting model does not work on machines, instead consumed container resources are accounted. If you need more resources, the cluster autoscaler will add additional worker nodes depending on the resource demands up to specified maxsize.

**Comment by fireba11** [comment]
I figured as much. We are replacing an existing cluster that has set a minsize (that one was provisioned for us) so i tried to set up the new one pretty much the same and stumbled over the minsize. The old cluster only had csi-lvm storage class available, so having more than one node was important for our DB cluster. With the replacement cluster we are switching over to the new partition-* storage class anyway :-)
