### ISSUE TITLE
postgres: cloudctl postgres edit enables to change description but this breaks connection to underlying zalando postgres

### ISSUE THREAD

**Issue by FrankEppink** [fi-ts/cloudctl#193]
It is possible to change the description i.e. the name via `cloudctl postgres edit <id>` so that the name is changed in e.g. `cloudctl postgres ls` but this breaks the connection to the underlying zalando postgres object.
Therefore following changes via `cloudctl postgres edit` are no longer reflected in the underlying  postgres edit <id>` so that the name is changed in e.g. `cloudctl postgres ls` but this breaks the connection to the underlying zalando postgres object

**Comment by eberlep** [comment]
This is already handled in the backend, so I am closing this issue here.

But the long term goal is to migrate the currenct `description` into a new field `name`, use that `name` field for the custom ressources and, once all partitions make use of that `name` field, allow chaning the `description` again.
